### PR TITLE
slides: improve syntax highlighting

### PR DESCRIPTION
**Pull request by davidchambers**
This pull request overhauls the syntax highlighting of code blocks in the slides. As a result ratios are now highlighted as numbers and the first value in a vector is now highlighted correctly. Additionally, the font and colours are more pleasing (though this is subjective).

__Before:__

Before

__After:__

After

### CODE REVIEW

**Comment by kpfell** [comment]
This has a :+1: from me, as the slides do indeed look way better this way!

However, alas, after all of the merging today, there are now apparently merge conflicts. So, :fist: for the moment!

**Comment by davidchambers** [comment]
I resolved the merge conflict. :)

**Comment by kpfell** [comment]
Yay, :+1: :+1:.

**Comment by bridgethillyer** [comment]
This is fantastic. :+1:

**Pull request merged**
