### PR TITLE
Make it clearer that x and y are placeholders.

### PR DESCRIPTION
**Pull request by joshhead**
The last slide in the intro uses x and y but does not explain what they are. Change the wording to show that `(quot x y)` is operating on x and y.

### CODE REVIEW

**Comment by davidchambers** [comment]
This change looks good. We should use [`rem`][1] rather than [`mod`][2], shouldn't we? (We're describing the function as the remainder function rather than as the modulus function.)


[1]: https://clojuredocs.org/clojure.core/rem
[2]: https://clojuredocs.org/clojure.core/mod

**Comment by joshhead** [comment]
Yes, that sounds like a good idea. I can change `mod` to `rem` here too.

**Comment by davidchambers** [comment]
:thumbsup:

**Comment by yokolet** [comment]
Looks good me as well. :+1:

**Pull request merged**
