### PR TITLE
added pdf version of student cheatsheet to be printed out  fixes #100

### LINKED ISSUE #100: Create cheatsheet for students
Create a cheatsheet with key syntax, function names, etc. that students are using in the exercises. A simple one-pager that could be printed out and used by students to help guide them during the exercises.

### PR DESCRIPTION
**Pull request by rubygeek**

### CODE REVIEW

**Comment by kpfell** [comment]
Yay! :tada: 

This is a super useful PR. :+1:, we will totally use this all of the time.

That said, should we name the file `ClojureBridgeCheatsheet.pdf`, or change the title at the top of the page to "Student Cheat Sheet"? Capitalization in the filename is slightly off.

**Comment by rubygeek** [comment]
fixed as suggested :) :)

**Comment by kpfell** [comment]
Alas! Now, the filename is misspelled, though.

"Cheatsheet" is actually "Cheatsheat" in the filename. ;)

**Comment by rubygeek** [comment]
arg .. I think its right now :)

**Comment by kpfell** [comment]
:+1: :+1: :+1: :+1: :+1: 

...though, one other person does still have to :+1: it. ;)

**Comment by davidchambers** [comment]
This is great! Would it be useful to include output in the "Creating a Vector" and "Creating a Map" sections? For example:

```clojure
(vector 1 2 3)
;=> [1 2 3]
[1 2 3 4]
;=> [1 2 3 4]
```

**Comment by rubygeek** [comment]
good idea, also added for maps and a version number on the document.. i
noticed today on the Clojure cheatsheet it has one and I just had those
printed and laminated today :)

On Sat, Jan 31, 2015 at 7:18 PM, David Chambers <notifications@github.com>
wrote:

> This is great! Would it be useful to include output in the "Creating a
> Vector" and "Creating a Map" sections? For example:
>
> (vector 1 2 3);=> [1 2 3]
> [1 2 3 4];=> [1 2 3 4]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClojureBridge/curriculum/pull/124#issuecomment-72346030>
> .
>



-- 
http://blog.rubygeek.com - my blog
http://www.linkedin.com/in/nolastowe - my linkedin profile
http://www.twitter.com/rubygeek - my twitter
http://github.com/rubygeek - my code

**Comment by davidchambers** [comment]
:+1:

**Comment by bridgethillyer** [comment]
This is *beautiful*. And just the right kind of examples. 

I printed it out, and it was a little hard to read. Does anyone know anything about fonts?? The print just needs to be a bit.... thicker? bolder? something like that.

**Comment by rubygeek** [comment]
You know I was thinking i might need to find a bolder font..  let me
experiment before ya'll merge it in..


On Mon, Feb 2, 2015 at 9:35 PM, Bridget Hillyer <notifications@github.com>
wrote:

> This is *beautiful*. And just the right kind of examples.
>
> I printed it out, and it was a little hard to read. Does anyone know
> anything about fonts?? The print just needs to be a bit.... thicker?
> bolder? something like that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ClojureBridge/curriculum/pull/124#issuecomment-72587020>
> .
>



-- 
http://blog.rubygeek.com - my blog
http://www.linkedin.com/in/nolastowe - my linkedin profile
http://www.twitter.com/rubygeek - my twitter
http://github.com/rubygeek - my code

**Comment by bridgethillyer** [comment]
This one is much easier to read. Thanks for working so hard on this, @rubygeek. Workshop participants will really enjoy this.

**Comment by davidchambers** [comment]
:clap:

**Pull request merged**
