### PR TITLE
Simpler initial map example.

### PR DESCRIPTION
**Pull request by brandonbloom**
More TA-training feedback.

### CODE REVIEW

**Comment by davidchambers** [comment]
Very nice!

**Comment by yokolet** [comment]
I'm going to merge this pull request, but reluctantly :grinning: 
I totally agree that `name` function is not a good choice. But, I'd like to stay away from math-y examples as much as possible. This "avoid math-y" is a request from Portland team.
In this case, the second example is more complicated math-y one. The `inc` would help to understand.

**Comment by yokolet** [comment]
aw, merging this pr killed prism highlighter. I'll fix the highlighter problem. this is probably because of Jekyll update on github side.

**Comment by brandonbloom** [comment]
I'd agree about math-y examples, but in this case, I can't think of anything else in core that would work with a clear unary operation on simple literals. Can you?

**Comment by yokolet** [comment]
@brandonbloom nope, at least for now. so, I merged the pull request :)

btw, highlighter was back. I updated gem versions and config to make out highlighter to work on current github pages.

**Pull request merged**
