### PR TITLE
Reword the share-per-person problem to be more clear

### PR DESCRIPTION
**Pull request by danevans**
This is how I understood the problem. Based on the names I would expect `total-with-tip` not to be changed and `share-per-person` to just be something like

```clj
(\ (total-with-tip subtotal tip-pct) people)
```

Addresses #134

### CODE REVIEW

**Comment by davidchambers** [comment]
:+1:

**Comment by kpfell** [comment]
Could you update the slides to match this change?

**Comment by danevans** [comment]
I thought these were the slides. I'd be happy to make the update but I'd appreciate a nudge in the right direction.

**Comment by danevans** [comment]
Ah, I think I found it here: https://github.com/ClojureBridge/curriculum/blob/master/outline/functions.md. Will do.

**Comment by danevans** [comment]
I modified the change to update the markdown.

**Comment by kpfell** [comment]
@danevans Ah, yes, sorry! I'm at Clojure/West and distractedly typed the wrong one of the two. :disappointed: 

But, yay! :+1:, merging.

**Pull request merged**
